### ISSUE TITLE
Failed to load JavaScript Standard Style library on Visual Studio Code

### ISSUE THREAD

**Issue by holopekochan** [chenxsan/vscode-standardjs#482]
What version of this package are you using? 2.1.2  standard engine 17.0.0
What operating system, Node.js, and npm version? npm 6.14.17 node v14.20.1

What happened? Failed to load JavaScript Standard Style library on Visual Studio Code Plugin

What did you expect to happen? load successfully

Are you willing to submit a pull request to fix this bug? no

I have installed the newest JS Standard plugin on visual studio code and installed the engine globally.
However, it failed to load. Visual Studio Code version 1.72.1. I have reopen VS code after installation.
```
[Info  - 6:41:32 a.m.] 
Failed to load the JavaScript Standard Style library for the document /home/user/test.js

To use JavaScript Standard Style please install JavaScript Standard Style by running 'npm install standard' in the workspace folder sdmc
or globally using 'npm install -g standard'. You need to reopen the workspace after installing JavaScript Standard Style.

Alternatively you can disable JavaScript Standard Style for the workspace folder sdmc by executing the 'Disable JavaScript Standard Style' command.
[Info  - 6:41:32 a.m.] 
Failed to load the JavaScript Standard Style library for the document /home/user/test.js

To use JavaScript Standard Style please install JavaScript Standard Style by running 'npm install standard' in the workspace folder sdmc
or globally using 'npm install -g standard'. You need to reopen the workspace after installing JavaScript Standard Style.

Alternatively you can disable JavaScript Standard Style for the workspace folder sdmc by executing the 'Disable JavaScript Standard Style' command.
```
```
$ sudo npm -g list --depth=n

npm WARN invalid config depth="n" set in command line options

npm WARN invalid config Must be one of: null, numeric value

/usr/local/lib

├── serverless@3.22.0

└── standard@17.0.0
```

```
    "standard.enable": true,
    "standard.enableGlobally": true,
    "standard.autoFixOnSave": true,
    "standard.usePackageJson": false
```

**Comment by holopekochan** [comment]
Also, tried to uninstall VS code from 1.72.1 and updated 1.72.2. Have the same error.

**Comment by holopekochan** [comment]
If I installed with npm install standard instead of --globally.
Same as https://github.com/standard/vscode-standard/issues/465
The following error shows
```
[Info  - 7:12:36 a.m.] JavaScript Standard Style server stopped.
[Info  - 7:12:36 a.m.] JavaScript Standard Style server is running.
[Info  - 7:12:36 a.m.] JavaScript Standard Style library loaded from: /home/user/node_modules/standard/index.js
TypeError: callback is not a function
    at /home/user/.vscode/extensions/standard.vscode-standard-2.1.2/server/out/server.js:667:17
TypeError: callback is not a function
    at /home/user/.vscode/extensions/standard.vscode-standard-2.1.2/server/out/server.js:667:17
TypeError: callback is not a function
    at /home/user/.vscode/extensions/standard.vscode-standard-2.1.2/server/out/server.js:667:17
TypeError: callback is not a function
    at /home/user/.vscode/extensions/standard.vscode-standard-2.1.2/server/out/server.js:667:17
```

This error does not show when I switch back to 2.12.0, however, autofix does not work.

looks like it is from here
https://github.com/standard/vscode-standard/blob/d8b17ac408d0f5fe86ff324ea936acfb961ccbee/server/src/server.ts#L1025

**Comment by holopekochan** [comment]
updated to node v16.18.0 from v14.20.1, solve the Failed to load JavaScript Standard Style library error.
Now, only having the problem with
```
TypeError: callback is not a function
    at /home/cyrus/.vscode/extensions/standard.vscode-standard-2.1.2/server/out/server.js:667:17
```
Will keep on track for this ticket. https://github.com/standard/vscode-standard/issues/465
